import React, { useState } from 'react';
import {
  View, Text, Image, TouchableOpacity,
  StyleSheet, SafeAreaView, FlatList,
  ActivityIndicator, Alert, Share,
  ScrollView,
} from 'react-native';
import RNFS from 'react-native-fs';

const STYLE_LABELS = {
  cartoon: '🎨 Cartoon',
  flat: '🎭 Flat Illustration',
  anime: '⛩️ Anime',
  pixel: '🕹️ Pixel Art',
  sketch: '✏️ Sketch',
  clay: '🧸 Clay 3D',
};

const QUICK_STYLES = [
  { id: 'advanced', icon: '🎛️', title: 'Advanced Tuner', sub: 'Adjust colors, line weight, or character intensity' },
  { id: 'different', icon: '🔄', title: 'Try Different Style', sub: 'Instantly swap to Synthwave, 3D Render, or Sketch' },
];

function ResultCard({ styleId, result, onRegenerate }) {
  const [intensity, setIntensity] = useState(85);

  const handleDownload = async () => {
    try {
      if (!result?.base64) return;
      const path = `${RNFS.DownloadDirectoryPath}/clipart_${styleId}_${Date.now()}.png`;
      await RNFS.writeFile(path, result.base64, 'base64');
      Alert.alert('Saved! ✅', 'Image saved to Downloads folder.');
    } catch (e) {
      Alert.alert('Error', 'Could not save image.');
    }
  };

  const handleShare = async () => {
    try {
      await Share.share({
        message: `Check out my ${STYLE_LABELS[styleId]} clipart generated by ClipArt AI!`,
        url: `data:image/png;base64,${result?.base64}`,
      });
    } catch (e) {}
  };

  return (
    <View style={styles.card}>

      {/* Header */}
      <View style={styles.cardHeader}>
        <TouchableOpacity onPress={onRegenerate}>
          <Text style={styles.backArrow}>←</Text>
        </TouchableOpacity>
        <Text style={styles.cardTitle}>{STYLE_LABELS[styleId] || styleId}</Text>
        <View style={styles.avatar}>
          <Text style={styles.avatarText}>AI</Text>
        </View>
      </View>

      {/* Image */}
      {!result && (
        <View style={styles.skeletonBox}>
          <ActivityIndicator color="#E8837A" size="large" />
          <Text style={styles.skeletonText}>Generating your masterpiece...</Text>
        </View>
      )}

      {result?.status === 'success' && (
        <>
          <View style={styles.imageWrapper}>
            <Image
              source={{ uri: `data:image/png;base64,${result.base64}` }}
              style={styles.resultImage}
              resizeMode="cover"
            />
            <View style={styles.afterBadge}>
              <Text style={styles.afterBadgeText}>AFTER</Text>
            </View>
            <View style={styles.promptBadge}>
              <Text style={styles.promptBadgeLeft}>ORIGINAL PROMPT</Text>
              <Text style={styles.promptBadgeRight}>{STYLE_LABELS[styleId]?.toUpperCase()} APPLIED</Text>
            </View>
          </View>

          {/* Intensity Slider */}
          <View style={styles.intensitySection}>
            <View style={styles.intensityHeader}>
              <Text style={styles.intensityLabel}>✦ Style Intensity</Text>
              <Text style={styles.intensityValue}>{intensity}%</Text>
            </View>
            <View style={styles.sliderTrack}>
              <View style={[styles.sliderFill, { width: `${intensity}%` }]} />
              <TouchableOpacity
                style={[styles.sliderThumb, { left: `${intensity - 3}%` }]}
                onPress={() => {}}
              />
            </View>
            <View style={styles.sliderLabels}>
              <Text style={styles.sliderLabelText}>SUBTLE</Text>
              <Text style={styles.sliderLabelText}>MAXIMUM MAGIC</Text>
            </View>
            {/* Intensity buttons */}
            <View style={styles.intensityBtns}>
              {[25, 50, 75, 100].map(val => (
                <TouchableOpacity
                  key={val}
                  style={[styles.intensityBtn, intensity === val && styles.intensityBtnActive]}
                  onPress={() => setIntensity(val)}>
                  <Text style={[styles.intensityBtnText, intensity === val && styles.intensityBtnTextActive]}>
                    {val}%
                  </Text>
                </TouchableOpacity>
              ))}
            </View>
          </View>

          {/* Prompt Refinement */}
          <View style={styles.promptSection}>
            <Text style={styles.promptSectionTitle}>✦ Prompt Refinement</Text>
            <View style={styles.promptBox}>
              <Text style={styles.promptBoxText}>
                A futuristic cityscape at night with neon lights and soft celestial glow, cinematic lighting, ultra-detailed {styleId} style
              </Text>
              <TouchableOpacity style={styles.promptEditBtn}>
                <Text style={styles.promptEditBtnText}>↗</Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Action Buttons */}
          <View style={styles.actionBtns}>
            <TouchableOpacity style={styles.downloadBtn} onPress={handleDownload}>
              <Text style={styles.downloadBtnText}>⬇ Download PNG</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.shareBtn} onPress={handleShare}>
              <Text style={styles.shareBtnText}>↗ Share Masterpiece</Text>
            </TouchableOpacity>
          </View>
        </>
      )}

      {result?.status === 'error' && (
        <View style={styles.errorBox}>
          <Text style={styles.errorText}>⚠️ Generation failed</Text>
          <TouchableOpacity style={styles.retryBtn} onPress={onRegenerate}>
            <Text style={styles.retryBtnText}>Try Again</Text>
          </TouchableOpacity>
        </View>
      )}

    </View>
  );
}

export default function ResultScreen({ results, selectedStyles, onBack, onRegenerate }) {
  const doneCount = selectedStyles.filter(s => results[s]).length;
  const total = selectedStyles.length;

  return (
    <SafeAreaView style={styles.safe}>

      {/* Progress bar */}
      <View style={styles.progressBar}>
        <View style={[styles.progressFill, { width: `${(doneCount / total) * 100}%` }]} />
      </View>

      <ScrollView showsVerticalScrollIndicator={false}>

        {/* All style results */}
        {selectedStyles.map(styleId => (
          <ResultCard
            key={styleId}
            styleId={styleId}
            result={results[styleId]}
            onRegenerate={onBack}
          />
        ))}

        {/* Quick Styles */}
        <View style={styles.quickStylesSection}>
          <Text style={styles.quickStylesTitle}>Quick Styles</Text>
          <View style={styles.quickStylesGrid}>
            {QUICK_STYLES.map(item => (
              <TouchableOpacity key={item.id} style={styles.quickStyleCard}>
                <Text style={styles.quickStyleIcon}>{item.icon}</Text>
                <Text style={styles.quickStyleName}>{item.title}</Text>
                <Text style={styles.quickStyleSub}>{item.sub}</Text>
              </TouchableOpacity>
            ))}
          </View>
        </View>

        {/* Regenerate */}
        <TouchableOpacity style={styles.regenerateBtn} onPress={onRegenerate}>
          <Text style={styles.regenerateBtnText}>🔄 Generate Again</Text>
        </TouchableOpacity>

        <View style={{ height: 40 }} />
      </ScrollView>

    </SafeAreaView>
  );
}

const PINK = '#E8837A';

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#FFF5F4' },

  progressBar: {
    height: 3, backgroundColor: '#F0E0DF',
    marginHorizontal: 0,
  },
  progressFill: { height: 3, backgroundColor: PINK },

  // Card
  card: {
    backgroundColor: '#fff',
    borderRadius: 24,
    margin: 16,
    marginBottom: 8,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingBottom: 8,
  },
  backArrow: { fontSize: 20, color: '#1A1A1A', fontWeight: '600' },
  cardTitle: { fontSize: 17, fontWeight: '700', color: '#1A1A1A' },
  avatar: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: PINK,
    alignItems: 'center', justifyContent: 'center',
  },
  avatarText: { color: '#fff', fontWeight: '800', fontSize: 12 },

  // Image
  imageWrapper: { position: 'relative' },
  resultImage: { width: '100%', height: 280 },
  afterBadge: {
    position: 'absolute', top: 12, left: 12,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4,
  },
  afterBadgeText: { fontSize: 11, fontWeight: '700', color: '#1A1A1A' },
  promptBadge: {
    position: 'absolute', bottom: 0, left: 0, right: 0,
    flexDirection: 'row', justifyContent: 'space-between',
    backgroundColor: 'rgba(0,0,0,0.4)',
    paddingHorizontal: 12, paddingVertical: 6,
  },
  promptBadgeLeft: { color: 'rgba(255,255,255,0.6)', fontSize: 9, fontWeight: '600' },
  promptBadgeRight: { color: 'rgba(255,255,255,0.6)', fontSize: 9, fontWeight: '600' },

  // Skeleton
  skeletonBox: {
    height: 280, alignItems: 'center',
    justifyContent: 'center', gap: 12,
    backgroundColor: '#FFF0EF',
  },
  skeletonText: { color: PINK, fontSize: 14, fontWeight: '600' },

  // Intensity
  intensitySection: { padding: 16, paddingBottom: 8 },
  intensityHeader: {
    flexDirection: 'row', justifyContent: 'space-between',
    marginBottom: 10,
  },
  intensityLabel: { fontSize: 13, fontWeight: '700', color: '#1A1A1A' },
  intensityValue: { fontSize: 13, fontWeight: '700', color: PINK },
  sliderTrack: {
    height: 4, backgroundColor: '#F0E0DF',
    borderRadius: 2, position: 'relative',
    marginBottom: 4,
  },
  sliderFill: { height: 4, backgroundColor: PINK, borderRadius: 2 },
  sliderThumb: {
    position: 'absolute', top: -8,
    width: 20, height: 20, borderRadius: 10,
    backgroundColor: PINK,
    elevation: 3,
  },
  sliderLabels: {
    flexDirection: 'row', justifyContent: 'space-between',
    marginTop: 6,
  },
  sliderLabelText: { fontSize: 9, color: '#BBB', fontWeight: '600' },
  intensityBtns: {
    flexDirection: 'row', gap: 8, marginTop: 12,
  },
  intensityBtn: {
    flex: 1, paddingVertical: 8,
    borderRadius: 10, borderWidth: 1.5,
    borderColor: '#EEE', alignItems: 'center',
  },
  intensityBtnActive: { backgroundColor: PINK, borderColor: PINK },
  intensityBtnText: { fontSize: 13, fontWeight: '600', color: '#999' },
  intensityBtnTextActive: { color: '#fff' },

  // Prompt
  promptSection: { paddingHorizontal: 16, paddingBottom: 12 },
  promptSectionTitle: { fontSize: 13, fontWeight: '700', color: '#1A1A1A', marginBottom: 8 },
  promptBox: {
    backgroundColor: '#FFF5F4',
    borderRadius: 12, padding: 12,
    flexDirection: 'row', alignItems: 'flex-start',
    gap: 8,
  },
  promptBoxText: { flex: 1, fontSize: 13, color: '#555', lineHeight: 20 },
  promptEditBtn: {
    width: 32, height: 32, borderRadius: 16,
    backgroundColor: PINK,
    alignItems: 'center', justifyContent: 'center',
  },
  promptEditBtnText: { color: '#fff', fontSize: 14, fontWeight: '700' },

  // Actions
  actionBtns: {
    flexDirection: 'row', gap: 10,
    padding: 16, paddingTop: 8,
  },
  downloadBtn: {
    flex: 1, backgroundColor: PINK,
    borderRadius: 50, paddingVertical: 14,
    alignItems: 'center',
    elevation: 3,
  },
  downloadBtnText: { color: '#fff', fontWeight: '700', fontSize: 14 },
  shareBtn: {
    flex: 1, backgroundColor: '#fff',
    borderRadius: 50, paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1.5, borderColor: '#EEE',
  },
  shareBtnText: { color: '#1A1A1A', fontWeight: '700', fontSize: 14 },

  // Error
  errorBox: {
    height: 150, alignItems: 'center',
    justifyContent: 'center', gap: 12,
  },
  errorText: { color: '#EF4444', fontSize: 15, fontWeight: '700' },
  retryBtn: {
    backgroundColor: PINK, borderRadius: 12,
    paddingHorizontal: 24, paddingVertical: 10,
  },
  retryBtnText: { color: '#fff', fontWeight: '700' },

  // Quick Styles
  quickStylesSection: { margin: 16, marginTop: 8 },
  quickStylesTitle: {
    fontSize: 18, fontWeight: '800',
    color: '#1A1A1A', marginBottom: 12,
  },
  quickStylesGrid: { flexDirection: 'row', gap: 12 },
  quickStyleCard: {
    flex: 1, backgroundColor: '#fff',
    borderRadius: 16, padding: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06, shadowRadius: 4,
  },
  quickStyleIcon: { fontSize: 24, marginBottom: 8 },
  quickStyleName: { fontSize: 14, fontWeight: '700', color: '#1A1A1A', marginBottom: 4 },
  quickStyleSub: { fontSize: 12, color: '#999', lineHeight: 18 },

  // Regenerate
  regenerateBtn: {
    marginHorizontal: 16,
    backgroundColor: '#fff',
    borderWidth: 2, borderColor: PINK,
    borderRadius: 50, paddingVertical: 16,
    alignItems: 'center',
  },
  regenerateBtnText: { color: PINK, fontSize: 16, fontWeight: '700' },
});